#+title:   Probability distributions
#+SUBTITLE: EBP038A05, 2020-2021
#+author: Nicky D. van Foreest
#+date: {{{time(%Y-%m-%d)}}}

* Overview

On this github page you can find all the material you need for the course on probability distributions.

*  Files

** Relevant for students

The directory =pdf-files= contains all relevant pdf files.
- Specifically, =pdf-file/course_overview.pdf= provides  all information about the organization of the course such as the schedule and grading
- =assignments/assignment-answer-template.tex=:  a  basic LaTeX  document that you  have to use as a template for your assignments.


** Irrelevant for students

You might be interested in the LaTeX sources of the study guide, or the other documents. If you're not, then just skip all this material.

- =common/abbreviations.sty=: abbreviations used in the tex files
- =common/preamble.sty=: necessary if you want to compile the files yourself.
- =lectures/=: sources for the lectures.
- =assignments=: sources for the assignments.
- =study-guide=: source material

* Updates of the material

Most of the assignments are new for this year. Hence there will be  mistakes. Please let us know, so that we can improve them.

- <2022-02-14 ma>, study guide: Added missing solutions to ch 7 and ch 9.
- <2022-02-15 di>: assignment ex 1.26: reformulation so that it is (hopefully) clear what you have to learn from this exercise.give an answer.
- <2022-02-16 wo>: assignment ex 1.24: reversed the arrival times of Alice and Bob in the code.
- <2022-02-18 vr>: updated the formulation of a few assignments here and there, but nothing major.
- <2022-02-24 do>: assignment 3: added #this to an exercise relating to BH-8.4.3.
- <2022-03-11 vr>: Use of Eve's law for BH.9.1


* Python

If you plan to use python, the best installation is perhaps [[https://www.anaconda.com/][anaconda]].
