#+title:   Probability distributions
#+SUBTITLE: EBP038A05, 2020-2021
#+author: Nicky D. van Foreest
#+date: {{{time(%Y-%m-%d)}}}

* Overview

All the material you need for the course on probability distributions.

*  Files

** Relevant for students

- =Course_overview.pdf=:  still to be made, all information about the course, schedule, grading, and so on
- =assigments/assignments.pdf=: the assignments.
- =assignments/assignment-answer-template.tex=:  a  basic LaTeX  document that you  have to use as a template for your assignments.
- =lectures/lectures-questions.pdf=: The questions (plus hints)  that we discuss during the lectures.
- =lectures/lectures-solutions.pdf=: The questions,  hints and solutions that we discuss during the lectures.
- =study-guide/study-guide.pdf=: Questions,  hints and solutions to help study the material.


** Irrelevant for students

- =common/abbreviations.sty=: abbreviations used in the tex files
- =common/preamble.sty=: necessary if you want to compile the files yourself.
- =lectures/lectures-demo.pdf=:  reformat the lecture material into slides, but no extra material.
